version: "latest"
services:
  web:
    build: .
    container_name: rdf-to-html
    working_dir: /code/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"